
services:
  postgres:
    image: postgres:15-alpine
    container_name: synergy-postgres
    environment:
      POSTGRES_USER: synergy
      POSTGRES_PASSWORD: synergy123
      POSTGRES_DB: synergy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synergy"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: synergy-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@soulsynergy.ru
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
